rquit
Add requirements.txt

C:\Users\Sathyasri\Desktop\estatebot> git push origin main
To https://github.com/divyasri-jegan-11/estatebot.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/divyasri-jegan-11/estatebot.git'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.# with '#' will be ignored, and an empty message aborts the commit.
t